name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_NAME=mydb" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancement des conteneurs dockers
        run: |
          docker build -t labo1-store-manager .
          docker compose up -d
      - name: Lancer les tests
        run: |
          cd src
          python3 -m pytest

      - name: Arrêter les conteneurs dockers
        run: |
          docker compose down

